[db_config]
postgres_host = "localhost"
postgres_port = 5432
postgres_user = "drunnn" #make sure he has privileges to create database
postgres_database = "asylum"

[delay]
entities_delay = 21600 # 6 hours
transactions_delay = 2 # 2 seconds

[execution_config]
max_entities_per_thread = 20
time_last = "1d"
limit = 10000

[webserver]
port = 80
limit_db_query = 10000