{
 "title": "Asylum dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Entity", "label": "Entity", "query": "SELECT name FROM entities" },
   {
    "name": "Addresses",
    "label": "Addresses",
    "query": "select address from unique_addresses  where name in IN (${Entity:singlequote});"
   },
   {
    "name": "moneytransferred",
    "label": "$ Transferred >",
    "query": "0, 1000, 10000, 100000, 1000000"
   },
   {
    "name": "name_tok",
    "label": "Token",
    "query": "SELECT DISTINCT token_symbol from transactions;"
   }
  ]
 },
 "panels": [
  {
   "title": "Monitored entities",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "-- SELECT name, website, twitter\n-- FROM entities\n-- WHERE name in (${Entity:singlequote})\n-- ORDER BY twitter DESC;\n\nSELECT entity_name,\n    SUM(balance_in_dollars::FLOAT) AS total_balance\nFROM \n    portfolio_holdings\nWHERE \n    (entity_name IN (${Entity:singlequote})) \n    AND \n    timestamp::numeric = (SELECT MAX(timestamp::numeric) FROM portfolio_holdings where (entity_name IN (${Entity:singlequote})))\nGROUP BY entity_name ORDER BY total_balance DESC\n"
    }
   ]
  },
  {
   "title": "Unique addresses",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "select name, address, CASE \n           WHEN chain = 'avalanche' THEN 'avalanche'\n           WHEN chain = 'base' THEN 'base'\n           WHEN chain = 'arbitrum_one' THEN 'arbitrum'\n           WHEN chain = 'ethereum' THEN 'eth'\n           WHEN chain = 'polygon' THEN 'polygon'\n           ELSE chain\n       END AS chain\n FROM unique_addresses WHERE name IN ( ${Entity:singlequote} );\n"
    }
   ]
  },
  {
   "title": "Portfolio holdings",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT UPPER(token_symbol),\n    SUM(balance_in_dollars::FLOAT) AS total_balance\nFROM \n    portfolio_holdings\nWHERE \n    (entity_name IN (${Entity:singlequote})) \n    AND \n    timestamp::numeric = (SELECT MAX(timestamp::numeric) FROM portfolio_holdings where (entity_name IN (${Entity:singlequote})))\nGROUP BY token_symbol;\n"
    }
   ]
  },
  {
   "title": "Total balance value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    balance_in_dollars::float AS total_balance\nFROM \n    portfolio_holdings\nWHERE \n    (entity_name IN (${Entity:singlequote})) \n    AND \n    timestamp::numeric = (SELECT MAX(timestamp::numeric) FROM portfolio_holdings where (entity_name IN (${Entity:singlequote})));\n"
    }
   ]
  },
  {
   "title": "Unique addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from unique_addresses where name in (${Entity:singlequote});"
    }
   ]
  },
  {
   "title": "Recent transactions",
   "type": "table",
   "gridPos": { "h": 39, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT block_timestamp, hash, from_entity_name, CONCAT(ROUND(amount::numeric, 2), ' ', token_symbol, ' ($', ROUND(dollar_amount::numeric, 2), ')') AS transfer_value, to_entity_name, \nCASE \n           WHEN chain = 'avalanche' THEN 'avalanche'\n           WHEN chain = 'base' THEN 'base'\n           WHEN chain = 'arbitrum_one' THEN 'arbitrum'\n           WHEN chain = 'ethereum' THEN 'eth'\n           WHEN chain = 'polygon' THEN 'polygon'\n           ELSE chain\n       END AS chain,\n       token_address, from_address, to_address, amount, token_symbol, dollar_amount\nFROM transactions WHERE (from_entity_name in (${Entity:singlequote}) OR to_entity_name in (${Entity:singlequote})) AND (from_address in (${Addresses:singlequote}) OR to_address in (${Addresses:singlequote})) AND  (dollar_amount::numeric >= $moneytransferred) AND (token_symbol in (${name_tok:singlequote}))  ORDER BY block_timestamp DESC LIMIT 1000 "
    }
   ]
  }
 ]
}