import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TransactionsTable from './components/TransactionsTable';
import Title from './components/Title';
import Spacer from "./components/Spacer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Title />
        <Spacer height="2rem" />
        <TransactionsTable /> 
        {children}
      </body>
    </html>
  );
}
